# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527a7c41ce2bb36de5e4b5e59f9d41da58ab026406b9710294f68cdb9a50b83094afdb6933e6263a0cdb49175f8c996fa8ab71ef9fc110bf2f438b8c167df9aa

test:
  secret_key_base: 2df1cacd8f9466f9dabeac49924bb5932c265e866cd29d6f85feca616a57803b9004369964f407d70b5e906e46758137f2f67f79e8f25190e600ce2fe6813ac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
